//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioProductos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suc_Pro
    {
        public int IdSucPro { get; set; }
        public int IdPro { get; set; }
        public int IdSuc { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual TProductos TProductos { get; set; }
        public virtual TSucursal TSucursal { get; set; }
    }
}
